version: '2'

volumes:
  ipfs_repo:

services:
  ipfs:
    build: .
    image: docker.io/fphammerle/ipfs
    container_name: ipfs
    volumes:
    - ipfs_repo:/ipfs-repo:rw
    ports:
    - '4001:4001'
    - '127.0.0.1:5001:5001'
    security_opt: [no-new-privileges]
    restart: unless-stopped

# https://docs.docker.com/compose/compose-file/compose-file-v2/
